server:
  port: 7000

spring:
  application:
    name: Gateway
  zuul:
    routes:
      movie:
        path: /**
        serviceId: movie
  eureka:
    client:
      service-url:
        default-zone:  http://localhost:8761/eureka